name: timetable_example
description: A simple example app for the flutter_enhanced_timetable package
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_enhanced_timetable:
    path: ../
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
